# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a54826ad3408db0fd0fb041faec6649cb44c74cdcbe28b65c9000fafa3393b40704bdee726bfff883f0327b1b1db580b737adaeaeaf8afc0a7fb4b7839e81f61

test:
  secret_key_base: 19ff7945120f56f732421878b377149cdecd9b3bc57335086a5808b0f560ff1984847035a6b1262a45ce8c56c7fbed347cc2bb9f17523918afebfa9e95f45257

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
